# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W5efEq6ySNnnI9XZSsbJy9flneg_FB1d
"""



"""username = postgres
password = vman1995
rds_url = database-1.cgkvp8uky6qx.us-west-1.rds.amazonaws.com
"""